version: "3.0"
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb-volume:/data/db
    networks:
      - dev-env-network
    ports:
      - "27017:27017"
  nginx:
    build:
      context: .
    depends_on:
      - backend-node
      - frontend-react
    restart: always
    networks:
      - dev-env-network
    ports:
      - "80:80"
  backend-node:
    image: node:18-alpine3.15
    depends_on:
      - mongodb
    restart: always
    volumes:
      - ../backend-node:/app
      - /app/node_modules
    networks:
      - dev-env-network
    expose:
      - "5611"
    working_dir: /app
    command: sh -c "npm install && npm run start"
  frontend-react:
    image: node:18-alpine3.15
    restart: always
    volumes:
      - ../frontend-react:/app
      - /app/node_modules
    networks:
      - dev-env-network
    expose:
      - "3000"
    working_dir: /app
    command: sh -c "npm install && npm run start"
networks:
  dev-env-network: 
volumes:
  mongodb-volume: